local ResManager =nil 
 ResManager = {	BugAnt = g_load_assets .. "ui/BugAnt.png",
	BugSpider = g_load_assets .. "ui/BugSpider.png",
	ExitButton = g_load_assets .. "ui/ExitButton.png",
	MainSceneBg = g_load_assets .. "ui/MainSceneBg.jpg",
	PlayButton = g_load_assets .. "ui/PlayButton.png",
	PlaySceneBg = g_load_assets .. "ui/PlaySceneBg.jpg",
	README = g_load_assets .. "ui/README.md",
	Star = g_load_assets .. "ui/Star.png",
	readRes = g_load_assets .. "readRes.py",
	resMap = g_load_assets .. "resMap.lua",
	resMap = g_load_assets .. "resMap.txt",
	BugDead = g_load_assets .. "audio/BugDead.wav",
	BugEnterHole = g_load_assets .. "audio/BugEnterHole.wav",
	README = g_load_assets .. "audio/README.md",
	check_box_active = g_load_assets .. "ui/defaul/check_box_active.png",
	check_box_active_disable = g_load_assets .. "ui/defaul/check_box_active_disable.png",
	check_box_active_press = g_load_assets .. "ui/defaul/check_box_active_press.png",
	check_box_normal = g_load_assets .. "ui/defaul/check_box_normal.png",
	check_box_normal_disable = g_load_assets .. "ui/defaul/check_box_normal_disable.png",
	check_box_normal_press = g_load_assets .. "ui/defaul/check_box_normal_press.png",
	scrollview_bg = g_load_assets .. "ui/defaul/scrollview_bg.png",
	tabview_bg = g_load_assets .. "ui/defaul/tabview_bg.png",
	tabview_btn1 = g_load_assets .. "ui/defaul/tabview_btn1.png",
	tabview_btn2 = g_load_assets .. "ui/defaul/tabview_btn2.png",
	text_field_bg = g_load_assets .. "ui/defaul/text_field_bg.png",
}
 return ResManager